### PR TITLE
Update dependencies to be compliant with PHP 7.2.5+

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Use latest version of header-stamp and use PHP 7.2.5+
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no

### CODE REVIEW

**Comment by PierreRambaud** [comment]
@Progi1984 @eternoendless Please, review and merge!

**Comment by eternoendless** [comment]
Review it yourself @PierreRambaud  ;)

**Comment by sowbiba** [comment]
> @Progi1984 @eternoendless Please, review and merge!

Faster!!! please

**Review by Progi1984 — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]
Looks good to me

**Pull request merged**
